name: login e2e tests
on:
  push:
    branches: [main]
  # schedule:
  #   # Menjalankan workflow setiap 1 menit
  #   - cron: "*/1 * * * *"

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      - name: Run a script
        run: echo "Hello, world! This action is running every 1 minutes."
