name: login e2e tests
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run --spec "cypress/e2e/3-techno-app/login.cy.js"
        uses: cypress-io/github-action@v6